### ISSUE TITLE
Error: Cannot find module 'jayson'

### ISSUE THREAD

**Issue by popey** [mkg20001/lbry-app-snap#1]
Tried lbry on my Ubuntu 16.04 system and it fails looking for jayson.

```
$ lbry 
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
App threw an error during load
Error: Cannot find module 'jayson'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/snap/lbry/3/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/lbry/3/app/main.js:4:16)
    at Object.<anonymous> (/snap/lbry/3/app/main.js:307:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'jayson'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/snap/lbry/3/app/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/lbry/3/app/main.js:4:16)
    at Object.<anonymous> (/snap/lbry/3/app/main.js:307:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by mkg20001** [comment]
Please see if this is fixed in rev 4.
