### ISSUE TITLE
App launches then closes after a minute or so

### ISSUE THREAD

**Issue by popey** [mkg20001/lbry-app-snap#2]
On 16.04. Using revision 7.

```
$ lbry
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Checking for lbrynet daemon
lbrynet daemon needs to be launched
Launching daemon: /snap/lbry/7/app/dist/lbrynet-daemon
2017-08-30 12:30:55,024 INFO     lbrynet.daemon.DaemonControl:81: Starting lbrynet-daemon from command line
2017-08-30 12:30:56,276 INFO     lbrynet.daemon.DaemonServer:64: Using non-authenticated API
2017-08-30 12:30:56,280 INFO     lbrynet.daemon.Daemon:241: Starting lbrynet-daemon
2017-08-30 12:30:56,580 INFO     lbrynet.daemon.ExchangeRateManager:174: Starting exchange rate manager
2017-08-30 12:30:57,925 INFO     lbrynet.daemon.Daemon:267: Platform: {"lbrynet_version": "0.14.2", "platform": "Linux-4.10.0-32-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.10.0-32-generic", "lbryum_version": "3.1.4", "ip": "82.16.62.66", "lbryschema_version": "0.0.9", "processor": "x86_64", "build": "release"}
2017-08-30 12:30:57,933 INFO     lbrynet.daemon.Daemon:460: Loading databases
2017-08-30 12:30:57,945 INFO     lbrynet.daemon.Daemon:524: Using lbryum wallet
2017-08-30 12:30:57,959 INFO     lbrynet.daemon.Daemon:1050: Get version info: {"lbrynet_version": "0.14.2", "platform": "Linux-4.10.0-32-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.10.0-32-generic", "lbryum_version": "3.1.4", "ip": "82.16.62.66", "lbryschema_version": "0.0.9", "processor": "x86_64", "build": "release"}
2017-08-30 12:31:00,971 WARNING  lbrynet.core.Session:243: UPnP failed. Reason: UnknownError
2017-08-30 12:31:00,971 INFO     lbrynet.core.Session:254: Starting DHT
2017-08-30 12:31:00,975 INFO     lbrynet.dht.protocol:216: DHT listening on UDP 4444
2017-08-30 12:31:00,977 INFO     lbrynet.core.RateLimiter:72: Starting <lbrynet.core.RateLimiter.RateLimiter object at 0x7fdcdad0fa10>
2017-08-30 12:31:00,977 INFO     lbrynet.core.BlobManager:97: Setting up the DiskBlobManager. blob_dir: /home/alan/snap/lbry/7/.local/share/lbry/lbrynet/blobfiles, db_file: /home/alan/snap/lbry/7/.local/share/lbry/lbrynet/blobs.db
2017-08-30 12:31:05,159 INFO     lbrynet.core.Wallet:1156: Loading the wallet
2017-08-30 12:31:05,396 ERROR    lbryum.interface:70: Failed to connect to (2, 1, 6, '', ('52.206.31.250', 50001))
Traceback (most recent call last):
  File "site-packages/lbryum/interface.py", line 65, in get_simple_socket
  File "socket.py", line 228, in meth
error: [Errno 111] Connection refused
2017-08-30 12:31:05,396 ERROR    lbryum.interface:70: Failed to connect to (2, 1, 6, '', ('52.206.31.250', 50001))
Traceback (most recent call last):
  File "site-packages/lbryum/interface.py", line 65, in get_simple_socket
  File "socket.py", line 228, in meth
error: [Errno 111] Connection refused
2017-08-30 12:31:05,472 ERROR    lbrynet.daemon.DaemonControl:112: Failed to startup
Traceback (most recent call last):
  File "site-packages/lbrynet/daemon/DaemonControl.py", line 109, in start_server_and_listen
FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: Failed to connect to network.
]]
2017-08-30 12:31:05,473 INFO     lbrynet.daemon.Daemon:389: Closing lbrynet session
2017-08-30 12:31:05,475 INFO     lbrynet.daemon.Daemon:390: Status at time of shutdown: loading_wallet
2017-08-30 12:31:05,476 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x7fdcd8cd08d0>
2017-08-30 12:31:05,477 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x7fdcd8cd0f50>
2017-08-30 12:31:05,478 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x7fdcdad0fa10>
2017-08-30 12:31:05,478 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x7fdcd8caf9d0>
2017-08-30 12:31:05,479 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x7fdcd8cafad0>
2017-08-30 12:31:05,480 INFO     lbrynet.core.Wallet:475: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x7fdcd8cafd50>
2017-08-30 12:31:05,481 INFO     lbrynet.core.Wallet:1207: Stopped wallet
2017-08-30 12:31:05,481 INFO     lbrynet.core.Wallet:1210: Stopped connection to lbryum server
2017-08-30 12:31:05,482 INFO     lbrynet.core.BlobManager:101: Stopping the DiskBlobManager
2017-08-30 12:31:05,483 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x7fdcd8cd08d0>
2017-08-30 12:31:05,485 INFO     lbrynet.dht.protocol:468: Stopping DHT
2017-08-30 12:31:05,485 INFO     lbrynet.dht.protocol:484: DHT stopped
2017-08-30 12:31:08,502 INFO     lbrynet.daemon.Daemon:389: Closing lbrynet session
2017-08-30 12:31:08,504 INFO     lbrynet.daemon.Daemon:390: Status at time of shutdown: loading_wallet
2017-08-30 12:31:08,505 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x7fdcd8cd08d0>
2017-08-30 12:31:08,505 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x7fdcd8cd0f50>
2017-08-30 12:31:08,505 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x7fdcdad0fa10>
2017-08-30 12:31:08,506 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x7fdcd8caf9d0>
2017-08-30 12:31:08,506 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x7fdcd8cafad0>
2017-08-30 12:31:08,506 INFO     lbrynet.core.Wallet:475: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x7fdcd8cafd50>
2017-08-30 12:31:08,507 INFO     lbrynet.core.Wallet:1207: Stopped wallet
2017-08-30 12:31:08,508 INFO     lbrynet.core.BlobManager:101: Stopping the DiskBlobManager
2017-08-30 12:31:08,508 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x7fdcd8cd08d0>
Unhandled error in Deferred:
2017-08-30 12:31:11,533 CRITICAL twisted:154: Unhandled error in Deferred:

2017-08-30 12:31:11,534 CRITICAL twisted:154: 
Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
  File "site-packages/lbrynet/core/BlobManager.py", line 102, in stop
  File "site-packages/twisted/enterprise/adbapi.py", line 397, in close
  File "site-packages/twisted/enterprise/adbapi.py", line 405, in finalClose
  File "site-packages/twisted/python/threadpool.py", line 274, in stop
  File "site-packages/twisted/_threads/_team.py", line 226, in quit
  File "site-packages/twisted/_threads/_convenience.py", line 35, in set
  File "site-packages/twisted/_threads/_convenience.py", line 46, in check
AlreadyQuit
The daemon has exited.
Did not request daemon stop, so quitting in 5 seconds.
Quitting.
alan@hal:~/Apps/android-studio/bin$ snap info lbry
name:      lbry
summary:   "LBRY is a fully decentralized, open-source protocol"
publisher: mkg20001
contact:   https://github.com/mkg20001/lbry-app-snap/issues
description: |
  LBRY is a fully decentralized, open-source protocol
  facilitating the discovery, access,
  and (sometimes) purchase of data.
  
commands:
  - lbry
tracking:    stable
installed:   0.14.3 (7) 122MB -
refreshed:   2017-08-14 11:20:25 +0100 BST
channels:               
  stable:    0.14.3 (7) 122MB -
  candidate: 0.14.3 (7) 122MB -
  beta:      0.14.3 (7) 122MB -
  edge:      0.14.3 (7) 122MB -
```

**Comment by mkg20001** [comment]
Apparmor issue. [keytar](https://npm.im/keytar) tries to access some key store over dbus which is denied.
